# Generated by Django 4.2.11 on 2024-07-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('type_contact', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('email', models.TextField(blank=True, max_length=255)),
            ],
        ),
    ]
