# Generated by Django 4.2.13 on 2024-08-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tel_book', '0002_book_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
