# Generated by Django 4.2.13 on 2024-09-20 12:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tel_book', '0004_book_user_alter_book_phone_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Telephone_book',
        ),
    ]
