# Generated by Django 5.1.2 on 2025-03-20 23:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tel_book', '0007_remove_contact_is_private_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date_create',
            field=models.DateField(default=datetime.datetime(2023, 3, 21, 0, 0), null=True),
        ),
    ]
