# Generated by Django 5.1.2 on 2025-03-20 23:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tel_book', '0008_contact_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_create',
            field=models.DateField(default=datetime.datetime(2023, 3, 21, 0, 0)),
        ),
    ]
